apiVersion: apps/v1
kind: Deployment
metadata:
  name: bonos
  namespace: casino
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bonos
  template:
    metadata:
      labels:
        app: bonos
    spec:
      containers:
        - name: bonos
          image: 851725353324.dkr.ecr.us-east-1.amazonaws.com/casino/bonos-service:latest
          ports:
            - containerPort: 8004
          env:
            - name: DB_HOST
              value: "postgres.casino.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_NAME